# This is a basic workflow to help you get started with Actions

name: Add Stars

on: [watch]

jobs:
  addstars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: add entry to readme
      run: |
        echo -e "\nUser [@${{github.actor}}](https://github.com/${{github.actor}}) liked the session and rated with a star" >> README.md 
    
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v4
      with:
        commitMessage: The repo received a new star rating from a user 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'main'
